name: Build and User Approval Workflow
on:
  push:
    branches:
      - master
jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
  Dev-Env:
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    environment:
      name: DEVENV
    steps:
      - name: 'Run some dev env steps'
        shell: pwsh
        run: |
          Write-Host 'Done some dev env deploy work'

  WaitForApproval:
    runs-on: ubuntu-latest
    needs: Dev-Env
    if: github.actor == 'ashoklogicfocus'
    steps:
      - name: 'Manual Approval'
        id: approve_step
        run: echo "User approval is required. User ${{ github.actor }} should approve."
      - name: 'Wait for Approval'
        id: wait_for_approval
        uses: arun291091/wait_for_approval_gha@v1
        with:
          base_repository_branch: master
          github_org: ashoklogicfocus
          repository_name: Task
          pr_reviewer: sarakishore
          time_limit: 20mins
          github_token: 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
