name: Build and User Approval Workflow
on:
  push:
    branches:
      - master

jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest

    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  User-Approval:
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: 'Request approval'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.NPM_TOKEN }}
          script: |
            const { data: { html_url: approveUrl } } = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: github.sha,
              environment: 'DEVENV',
              transient_environment: true,
            });
            await github.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              content: 'eyes',
            });
            core.setOutput('approval-url', approveUrl);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Dev-Env:
    runs-on: ubuntu-latest
    needs: User-Approval
    if: github.event_name == 'deployment' && github.event.deployment.environment == 'DEVENV' && github.event.deployment.statuses[0].state == 'success'
    steps:
      - name: 'Run some dev env steps'
        shell: pwsh
        run: |
          Write-Host 'Done some dev env deploy work'
